/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/hilu-ril/modelHiluNB.glb -o src/components/ModeHiluNBRill.jsx -k -K -r public 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function ModeHiluNBRill(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/hilu-ril/modelHiluNB.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" scale={19.249}>
          <group name="Armature001">
            <primitive object={nodes.Locator} />
            <skinnedMesh name="Back_Comb" geometry={nodes.Back_Comb.geometry} material={materials['YAMA Comb & Wattles.001']} skeleton={nodes.Back_Comb.skeleton} />
            <skinnedMesh name="Body_1" geometry={nodes.Body_1.geometry} material={materials['YAMA Skin.001']} skeleton={nodes.Body_1.skeleton} />
            <group name="BodyArmor">
              <skinnedMesh name="Cube055" geometry={nodes.Cube055.geometry} material={materials['YAMA Mecha Body.003']} skeleton={nodes.Cube055.skeleton} />
              <skinnedMesh name="Cube055_1" geometry={nodes.Cube055_1.geometry} material={materials['MAKA Watermark.001']} skeleton={nodes.Cube055_1.skeleton} />
            </group>
            <skinnedMesh name="Fingers001" geometry={nodes.Fingers001.geometry} material={materials['YAMA Skin.001']} skeleton={nodes.Fingers001.skeleton} />
            <skinnedMesh name="Fingers002" geometry={nodes.Fingers002.geometry} material={materials['YAMA Skin.001']} skeleton={nodes.Fingers002.skeleton} />
            <skinnedMesh name="Fingers003" geometry={nodes.Fingers003.geometry} material={materials['YAMA Skin.001']} skeleton={nodes.Fingers003.skeleton} />
            <skinnedMesh name="Fingers004" geometry={nodes.Fingers004.geometry} material={materials['YAMA Skin.001']} skeleton={nodes.Fingers004.skeleton} />
            <skinnedMesh name="Fingers005" geometry={nodes.Fingers005.geometry} material={materials['YAMA Skin.001']} skeleton={nodes.Fingers005.skeleton} />
            <skinnedMesh name="Fingers016" geometry={nodes.Fingers016.geometry} material={materials['YAMA Skin.001']} skeleton={nodes.Fingers016.skeleton} />
            <skinnedMesh name="Fingers017" geometry={nodes.Fingers017.geometry} material={materials['YAMA Skin.001']} skeleton={nodes.Fingers017.skeleton} />
            <skinnedMesh name="Fingers018" geometry={nodes.Fingers018.geometry} material={materials['YAMA Skin.001']} skeleton={nodes.Fingers018.skeleton} />
            <skinnedMesh name="Fingers019" geometry={nodes.Fingers019.geometry} material={materials['YAMA Skin.001']} skeleton={nodes.Fingers019.skeleton} />
            <skinnedMesh name="Fingers020" geometry={nodes.Fingers020.geometry} material={materials['YAMA Skin.001']} skeleton={nodes.Fingers020.skeleton} />
            <skinnedMesh name="Front_Comb" geometry={nodes.Front_Comb.geometry} material={materials['YAMA Comb & Wattles.001']} skeleton={nodes.Front_Comb.skeleton} />
            <skinnedMesh name="HandL_1" geometry={nodes.HandL_1.geometry} material={materials['Blue Edge Glow.001']} skeleton={nodes.HandL_1.skeleton} />
            <skinnedMesh name="HandR_1" geometry={nodes.HandR_1.geometry} material={materials['Blue Edge Glow.001']} skeleton={nodes.HandR_1.skeleton} />
            <group name="L_Armor">
              <skinnedMesh name="Cube019" geometry={nodes.Cube019.geometry} material={materials['YAMA Mecha Body.003']} skeleton={nodes.Cube019.skeleton} />
              <skinnedMesh name="Cube019_1" geometry={nodes.Cube019_1.geometry} material={materials['YAMA Mecha Armor.001']} skeleton={nodes.Cube019_1.skeleton} />
            </group>
            <skinnedMesh name="L_Body_Armor" geometry={nodes.L_Body_Armor.geometry} material={materials['YAMA Mecha Body.003']} skeleton={nodes.L_Body_Armor.skeleton} />
            <skinnedMesh name="L_Arm" geometry={nodes.L_Arm.geometry} material={materials['YAMA Arms .001']} skeleton={nodes.L_Arm.skeleton} />
            <skinnedMesh name="L_LEG" geometry={nodes.L_LEG.geometry} material={materials['YAMA Limbs.001']} skeleton={nodes.L_LEG.skeleton} />
            <skinnedMesh name="L_LEGArmor" geometry={nodes.L_LEGArmor.geometry} material={materials['YAMA Mecha Armor.001']} skeleton={nodes.L_LEGArmor.skeleton} />
            <skinnedMesh name="L_LEGFoot" geometry={nodes.L_LEGFoot.geometry} material={materials['Blue Edge Glow.001']} skeleton={nodes.L_LEGFoot.skeleton} />
            <skinnedMesh name="L_LEGFoot001" geometry={nodes.L_LEGFoot001.geometry} material={materials['Blue Edge Glow.001']} skeleton={nodes.L_LEGFoot001.skeleton} />
            <skinnedMesh name="R_Body_Armor" geometry={nodes.R_Body_Armor.geometry} material={materials['YAMA Mecha Body.003']} skeleton={nodes.R_Body_Armor.skeleton} />
            <group name="RArmor">
              <skinnedMesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials['YAMA Mecha Body.003']} skeleton={nodes.Cube005.skeleton} />
              <skinnedMesh name="Cube005_1" geometry={nodes.Cube005_1.geometry} material={materials['YAMA Mecha Armor.001']} skeleton={nodes.Cube005_1.skeleton} />
            </group>
            <skinnedMesh name="R_Arm" geometry={nodes.R_Arm.geometry} material={materials['YAMA Arms .001']} skeleton={nodes.R_Arm.skeleton} />
            <skinnedMesh name="R_LEG" geometry={nodes.R_LEG.geometry} material={materials['YAMA Limbs.001']} skeleton={nodes.R_LEG.skeleton} />
            <skinnedMesh name="R_LEGArmor" geometry={nodes.R_LEGArmor.geometry} material={materials['YAMA Mecha Armor.001']} skeleton={nodes.R_LEGArmor.skeleton} />
            <skinnedMesh name="Tail_1" geometry={nodes.Tail_1.geometry} material={materials['YAMA Mecha Tail.001']} skeleton={nodes.Tail_1.skeleton} />
            <skinnedMesh name="Eyeball" geometry={nodes.Eyeball.geometry} material={materials['BLACK.001']} skeleton={nodes.Eyeball.skeleton} morphTargetDictionary={nodes.Eyeball.morphTargetDictionary} morphTargetInfluences={nodes.Eyeball.morphTargetInfluences} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/hilu-ril/modelHiluNB.glb')
