/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/map-bake/model.glb -o src/components/ModelMapNotBake.jsx -k -K -r public 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function ModelMapBake(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/map-bake/model.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sphere003" position={[-0.989, 0.462, 1.509]} rotation={[-2.749, -1.013, -2.804]} scale={0.146} />
        <group name="Empty001" position={[-1.487, 0.462, 1.223]} scale={0.101} />
        <group name="GROUND001" position={[0, 0.223, -1.743]} scale={[5.39, 4.857, 7.354]}>
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['terrain.green']} />
          <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials.Ground} />
        </group>
        <group name="Text001" position={[-1.117, 0.281, 1.567]} rotation={[Math.PI / 2, 0, -2.376]} scale={0.08}>
          <mesh name="Text004" geometry={nodes.Text004.geometry} material={materials['Material.135']} />
          <mesh name="Text004_1" geometry={nodes.Text004_1.geometry} material={materials['base.001']} />
          <mesh name="Text004_2" geometry={nodes.Text004_2.geometry} material={materials['roof.016']} />
          <mesh name="Text004_3" geometry={nodes.Text004_3.geometry} material={materials['Material.141']} />
          <mesh name="Text004_4" geometry={nodes.Text004_4.geometry} material={materials['tree.001']} />
          <mesh name="Text004_5" geometry={nodes.Text004_5.geometry} material={materials['Material.138']} />
        </group>
        <group name="Sphere002" position={[-0.989, 0.462, 1.509]} rotation={[-2.774, -0.974, -2.825]} scale={0.146}>
          <mesh name="Sphere024" geometry={nodes.Sphere024.geometry} material={materials['Material.139']} />
          <mesh name="Sphere024_1" geometry={nodes.Sphere024_1.geometry} material={materials['roof.015']} />
        </group>
        <group name="Cube051" position={[-1.9, 0.371, 0.858]} rotation={[-1.251, -0.78, -1.131]} scale={[0.016, 0.019, 0.019]}>
          <mesh name="Cube173" geometry={nodes.Cube173.geometry} material={materials['Material.155']} />
          <mesh name="Cube173_1" geometry={nodes.Cube173_1.geometry} material={materials['Material.150']} />
          <mesh name="Cube173_2" geometry={nodes.Cube173_2.geometry} material={materials['Material.151']} />
          <mesh name="Cube173_3" geometry={nodes.Cube173_3.geometry} material={materials['Material.148']} />
          <mesh name="Cube173_4" geometry={nodes.Cube173_4.geometry} material={materials['base light.005']} />
          <mesh name="Cube173_5" geometry={nodes.Cube173_5.geometry} material={materials['Material.143']} />
        </group>
        <group name="Cube050" position={[-2.066, 0.277, 0.659]} rotation={[0, -1.263, 0]} scale={[0.005, 0.039, 0.01]}>
          <mesh name="Cube172" geometry={nodes.Cube172.geometry} material={materials['Material.154']} />
          <mesh name="Cube172_1" geometry={nodes.Cube172_1.geometry} material={materials['Material.153']} />
          <mesh name="Cube172_2" geometry={nodes.Cube172_2.geometry} material={materials.Material} />
          <mesh name="Cube172_3" geometry={nodes.Cube172_3.geometry} material={materials['Wood 2']} />
          <mesh name="Cube172_4" geometry={nodes.Cube172_4.geometry} material={materials['Tree 2 green']} />
          <mesh name="Cube172_5" geometry={nodes.Cube172_5.geometry} material={materials['Material.145']} />
          <mesh name="Cube172_6" geometry={nodes.Cube172_6.geometry} material={materials['Material.146']} />
          <mesh name="Cube172_7" geometry={nodes.Cube172_7.geometry} material={materials['Material.147']} />
          <mesh name="Cube172_8" geometry={nodes.Cube172_8.geometry} material={materials['Material.144']} />
        </group>
        <group name="Commercial_building_lowpoly_08038" position={[-1.931, 0.291, 0.867]} rotation={[0, -0.634, 0]} scale={0.239}>
          <mesh name="Cube177" geometry={nodes.Cube177.geometry} material={materials['base.024']} />
          <mesh name="Cube177_1" geometry={nodes.Cube177_1.geometry} material={materials['glass.029']} />
          <mesh name="Cube177_2" geometry={nodes.Cube177_2.geometry} material={materials['roof.019']} />
          <mesh name="Cube177_3" geometry={nodes.Cube177_3.geometry} material={materials['base.031']} />
          <mesh name="Cube177_4" geometry={nodes.Cube177_4.geometry} material={materials['glass.032']} />
          <mesh name="Cube177_5" geometry={nodes.Cube177_5.geometry} material={materials['glass.023']} />
        </group>
        <group name="Commercial_building_lowpoly_04092" position={[-2.306, 0.229, 0.908]} rotation={[0, -1.263, 0]} scale={0.239}>
          <mesh name="Circle027" geometry={nodes.Circle027.geometry} material={nodes.Circle027.material} />
          <mesh name="Circle027_1" geometry={nodes.Circle027_1.geometry} material={nodes.Circle027_1.material} />
        </group>
        <group name="Commercial_building_lowpoly_04091" position={[-2.306, 0.229, 0.908]} rotation={[0, -1.263, 0]} scale={0.239}>
          <mesh name="Circle028" geometry={nodes.Circle028.geometry} material={nodes.Circle028.material} />
          <mesh name="Circle028_1" geometry={nodes.Circle028_1.geometry} material={nodes.Circle028_1.material} />
        </group>
        <group name="Commercial_building_lowpoly_04037" position={[-2.306, 0.229, 0.908]} rotation={[0, -1.263, 0]} scale={0.239}>
          <mesh name="Cone057" geometry={nodes.Cone057.geometry} material={nodes.Cone057.material} />
          <mesh name="Cone057_1" geometry={nodes.Cone057_1.geometry} material={nodes.Cone057_1.material} />
        </group>
        <group name="Commercial_building_lowpoly_04035" position={[-2.306, 0.229, 0.908]} rotation={[0, -1.263, 0]} scale={0.239}>
          <mesh name="Cone058" geometry={nodes.Cone058.geometry} material={nodes.Cone058.material} />
          <mesh name="Cone058_1" geometry={nodes.Cone058_1.geometry} material={nodes.Cone058_1.material} />
        </group>
        <group name="Cylinder024" position={[-3.489, 0.292, 2.374]} rotation={[-0.029, 0, -0.075]} scale={0.259}>
          <mesh name="Cylinder068" geometry={nodes.Cylinder068.geometry} material={materials['Material.179']} />
          <mesh name="Cylinder068_1" geometry={nodes.Cylinder068_1.geometry} material={materials['base.027']} />
          <mesh name="Cylinder068_2" geometry={nodes.Cylinder068_2.geometry} material={materials['Material.156']} />
          <mesh name="Cylinder068_3" geometry={nodes.Cylinder068_3.geometry} material={materials['Material.177']} />
          <mesh name="Cylinder068_4" geometry={nodes.Cylinder068_4.geometry} material={materials['Material.178']} />
          <mesh name="Cylinder068_5" geometry={nodes.Cylinder068_5.geometry} material={materials['base.026']} />
          <mesh name="Cylinder068_6" geometry={nodes.Cylinder068_6.geometry} material={materials['glass.002']} />
        </group>
        <group name="Commercial_building_lowpoly_05013" position={[-3.572, 0.266, 2.435]} rotation={[0, 0.687, 0]} scale={0.42}>
          <mesh name="Cone060" geometry={nodes.Cone060.geometry} material={materials['tree.013']} />
          <mesh name="Cone060_1" geometry={nodes.Cone060_1.geometry} material={materials['WOOD.011']} />
        </group>
        <group name="Cylinder002" position={[-3.489, 0.292, 2.374]} rotation={[-0.029, 0, -0.075]} scale={0.259}>
          <mesh name="Cylinder002_1" geometry={nodes.Cylinder002_1.geometry} material={materials['Material.181']} />
          <mesh name="Cylinder002_2" geometry={nodes.Cylinder002_2.geometry} material={materials['Material.157']} />
          <mesh name="Cylinder002_3" geometry={nodes.Cylinder002_3.geometry} material={materials['Material.158']} />
          <mesh name="Cylinder002_4" geometry={nodes.Cylinder002_4.geometry} material={materials['Material.159']} />
          <mesh name="Cylinder002_5" geometry={nodes.Cylinder002_5.geometry} material={materials['Material.180']} />
          <mesh name="Cylinder002_6" geometry={nodes.Cylinder002_6.geometry} material={materials['Material.160']} />
          <mesh name="Cylinder002_7" geometry={nodes.Cylinder002_7.geometry} material={materials['Material.161']} />
          <mesh name="Cylinder002_8" geometry={nodes.Cylinder002_8.geometry} material={materials['Material.162']} />
          <mesh name="Cylinder002_9" geometry={nodes.Cylinder002_9.geometry} material={materials['Material.163']} />
          <mesh name="Cylinder002_10" geometry={nodes.Cylinder002_10.geometry} material={materials['Material.164']} />
          <mesh name="Cylinder002_11" geometry={nodes.Cylinder002_11.geometry} material={materials['Material.165']} />
          <mesh name="Cylinder002_12" geometry={nodes.Cylinder002_12.geometry} material={materials['Material.166']} />
          <mesh name="Cylinder002_13" geometry={nodes.Cylinder002_13.geometry} material={materials['Material.167']} />
          <mesh name="Cylinder002_14" geometry={nodes.Cylinder002_14.geometry} material={materials['Material.168']} />
          <mesh name="Cylinder002_15" geometry={nodes.Cylinder002_15.geometry} material={materials['Material.170']} />
          <mesh name="Cylinder002_16" geometry={nodes.Cylinder002_16.geometry} material={materials['Material.172']} />
          <mesh name="Cylinder002_17" geometry={nodes.Cylinder002_17.geometry} material={materials['Material.173']} />
          <mesh name="Cylinder002_18" geometry={nodes.Cylinder002_18.geometry} material={materials['Material.174']} />
          <mesh name="Cylinder002_19" geometry={nodes.Cylinder002_19.geometry} material={materials['Material.175']} />
        </group>
        <group name="Text002" position={[-2.736, 0.56, 3.043]} rotation={[1.569, -0.01, 0.179]} scale={0.153}>
          <mesh name="Text005" geometry={nodes.Text005.geometry} material={materials['roof.001']} />
          <mesh name="Text005_1" geometry={nodes.Text005_1.geometry} material={materials['base.003']} />
          <mesh name="Text005_2" geometry={nodes.Text005_2.geometry} material={materials['Material.001']} />
          <mesh name="Text005_3" geometry={nodes.Text005_3.geometry} material={materials['Material.189']} />
          <mesh name="Text005_4" geometry={nodes.Text005_4.geometry} material={materials['Material.188']} />
          <mesh name="Text005_5" geometry={nodes.Text005_5.geometry} material={materials['Material.187']} />
          <mesh name="Text005_6" geometry={nodes.Text005_6.geometry} material={materials['Material.186']} />
          <mesh name="Text005_7" geometry={nodes.Text005_7.geometry} material={materials['Material.184']} />
        </group>
        <mesh name="Cube073" geometry={nodes.Cube073.geometry} material={nodes.Cube073.material} position={[-2.481, 0.639, 3.374]} rotation={[0.025, 1.191, -0.028]} scale={[0.006, 0.004, 0.015]} />
        <group name="Cube071" position={[-2.521, 0.383, 3.337]} rotation={[0.014, 0.968, -0.018]} scale={0.251}>
          <mesh name="Cube198" geometry={nodes.Cube198.geometry} material={materials['Material.191']} />
          <mesh name="Cube198_1" geometry={nodes.Cube198_1.geometry} material={materials['Material.190']} />
          <mesh name="Cube198_2" geometry={nodes.Cube198_2.geometry} material={materials['base.002']} />
          <mesh name="Cube198_3" geometry={nodes.Cube198_3.geometry} material={materials['glass.001']} />
          <mesh name="Cube198_4" geometry={nodes.Cube198_4.geometry} material={materials['Material.183']} />
          <mesh name="Cube198_5" geometry={nodes.Cube198_5.geometry} material={materials['Material.182']} />
        </group>
        <group name="Cube056" position={[-2.481, 0.635, 3.374]} rotation={[0.025, 1.191, -0.028]} scale={0.002}>
          <mesh name="Cube183" geometry={nodes.Cube183.geometry} material={materials['base.029']} />
          <mesh name="Cube183_1" geometry={nodes.Cube183_1.geometry} material={materials['roof.021']} />
        </group>
        <group name="Cube090" position={[-1.164, 0.255, 2.833]} rotation={[-Math.PI, 0.859, -Math.PI]} scale={0.019}>
          <mesh name="Cube218" geometry={nodes.Cube218.geometry} material={materials['Material.005']} />
          <mesh name="Cube218_1" geometry={nodes.Cube218_1.geometry} material={materials['Material.198']} />
          <mesh name="Cube218_2" geometry={nodes.Cube218_2.geometry} material={materials['roof.020']} />
          <mesh name="Cube218_3" geometry={nodes.Cube218_3.geometry} material={materials['base.029']} />
          <mesh name="Cube218_4" geometry={nodes.Cube218_4.geometry} material={materials['glass.031']} />
        </group>
        <group name="Sphere008" position={[-1.474, 0.45, 3.103]} rotation={[-2.739, 0.634, -2.967]} scale={0.028}>
          <mesh name="Sphere033" geometry={nodes.Sphere033.geometry} material={materials['Material.193']} />
          <mesh name="Sphere033_1" geometry={nodes.Sphere033_1.geometry} material={materials['Material.006']} />
          <mesh name="Sphere033_2" geometry={nodes.Sphere033_2.geometry} material={materials['Material.199']} />
          <mesh name="Sphere033_3" geometry={nodes.Sphere033_3.geometry} material={materials['Skate.005']} />
          <mesh name="Sphere033_4" geometry={nodes.Sphere033_4.geometry} material={materials['Skate.006']} />
          <mesh name="Sphere033_5" geometry={nodes.Sphere033_5.geometry} material={materials['RED.004']} />
          <mesh name="Sphere033_6" geometry={nodes.Sphere033_6.geometry} material={materials['Material.196']} />
        </group>
        <group name="Cube002" position={[-1.164, 0.254, 2.833]} rotation={[-Math.PI, 0.859, -Math.PI]} scale={0.019}>
          <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['paper.003']} />
          <mesh name="Cube003_1" geometry={nodes.Cube003_1.geometry} material={materials['red.002']} />
          <mesh name="Cube003_2" geometry={nodes.Cube003_2.geometry} material={materials['blue.002']} />
          <mesh name="Cube003_3" geometry={nodes.Cube003_3.geometry} material={materials['orange.002']} />
        </group>
        <group name="Cylinder033" position={[-1.425, 0.35, 3.019]} rotation={[-0.011, -0.514, -0.035]} scale={[0.004, 0.008, 0.004]}>
          <mesh name="Cylinder072" geometry={nodes.Cylinder072.geometry} material={materials['RED.005']} morphTargetDictionary={nodes.Cylinder072.morphTargetDictionary} morphTargetInfluences={nodes.Cylinder072.morphTargetInfluences} />
          <mesh name="Cylinder072_1" geometry={nodes.Cylinder072_1.geometry} material={materials['BLACK.001']} morphTargetDictionary={nodes.Cylinder072_1.morphTargetDictionary} morphTargetInfluences={nodes.Cylinder072_1.morphTargetInfluences} />
          <mesh name="Cylinder072_2" geometry={nodes.Cylinder072_2.geometry} material={materials['Skin.002']} morphTargetDictionary={nodes.Cylinder072_2.morphTargetDictionary} morphTargetInfluences={nodes.Cylinder072_2.morphTargetInfluences} />
          <mesh name="Cylinder072_3" geometry={nodes.Cylinder072_3.geometry} material={materials['WHITE.001']} morphTargetDictionary={nodes.Cylinder072_3.morphTargetDictionary} morphTargetInfluences={nodes.Cylinder072_3.morphTargetInfluences} />
          <mesh name="Cylinder072_4" geometry={nodes.Cylinder072_4.geometry} material={materials['YELLOW.002']} morphTargetDictionary={nodes.Cylinder072_4.morphTargetDictionary} morphTargetInfluences={nodes.Cylinder072_4.morphTargetInfluences} />
          <mesh name="Cylinder072_5" geometry={nodes.Cylinder072_5.geometry} material={materials['SHADE 1.001']} morphTargetDictionary={nodes.Cylinder072_5.morphTargetDictionary} morphTargetInfluences={nodes.Cylinder072_5.morphTargetInfluences} />
        </group>
        <group name="Cylinder001" position={[-1.425, 0.35, 3.019]} rotation={[-0.011, -0.514, -0.035]} scale={[0.004, 0.008, 0.004]}>
          <mesh name="Cylinder001_1" geometry={nodes.Cylinder001_1.geometry} material={materials['BLACK.001']} morphTargetDictionary={nodes.Cylinder001_1.morphTargetDictionary} morphTargetInfluences={nodes.Cylinder001_1.morphTargetInfluences} />
          <mesh name="Cylinder001_2" geometry={nodes.Cylinder001_2.geometry} material={materials['WHITE.001']} morphTargetDictionary={nodes.Cylinder001_2.morphTargetDictionary} morphTargetInfluences={nodes.Cylinder001_2.morphTargetInfluences} />
          <mesh name="Cylinder001_3" geometry={nodes.Cylinder001_3.geometry} material={materials['YELLOW.002']} morphTargetDictionary={nodes.Cylinder001_3.morphTargetDictionary} morphTargetInfluences={nodes.Cylinder001_3.morphTargetInfluences} />
          <mesh name="Cylinder001_4" geometry={nodes.Cylinder001_4.geometry} material={materials['SHADE 1.001']} morphTargetDictionary={nodes.Cylinder001_4.morphTargetDictionary} morphTargetInfluences={nodes.Cylinder001_4.morphTargetInfluences} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/map-bake/model.glb')
