/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/space-ship.glb -o src/components/SpaceShip.jsx -k -K -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function SpaceShip(props) {
  const { nodes, materials } = useGLTF('/space-ship.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="base-image" position={[0, 2.483, -3.998]} rotation={[Math.PI / 2, 0, 0]} />
        <group name="Cylinder" position={[1.1, 0.793, 0]} rotation={[0, 0, -0.698]} scale={[24.848, 23.232, 23.232]}>
          <mesh name="Cylinder_1" geometry={nodes.Cylinder_1.geometry} material={materials['base-color']} />
          <mesh name="Cylinder_2" geometry={nodes.Cylinder_2.geometry} material={materials.wings} />
        </group>
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.wings} position={[-42.706, -51.051, 0]} rotation={[-Math.PI / 2, -0.873, -Math.PI / 2]} scale={23.232} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.wings} position={[-42.706, -51.051, 0]} rotation={[0, 0, -0.698]} scale={23.232} />
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials.wings} position={[-42.706, -51.051, 0]} rotation={[0, 0, -0.698]} scale={23.232} />
        <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials.fire} position={[-42.706, -51.051, 0]} rotation={[0, 0, -0.698]} scale={23.232} />
      </group>
    </group>
  )
}

useGLTF.preload('/space-ship.glb')
