/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/space-ship-scaled.glb -o src/components/SpaceShipScaled.jsx -k -K -r public 
*/

import { useGLTF } from "@react-three/drei";

export function SpaceShipScaled(props) {
  const { nodes, materials } = useGLTF("/space-ship-scaled.glb");
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group
          name="base-image"
          position={[0, 2.483, -3.998]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <group
          name="Cylinder"
          position={[0.258, 6.445, 0]}
          rotation={[0, 0, -0.002]}
          scale={[1.813, 1.695, 1.695]}
        >
          <mesh
            name="Cylinder_1"
            geometry={nodes.Cylinder_1.geometry}
            material={materials["base-color"]}
          />
          <mesh
            name="Cylinder_2"
            geometry={nodes.Cylinder_2.geometry}
            material={materials.wings}
          />
        </group>
        <mesh
          name="Cube"
          geometry={nodes.Cube.geometry}
          material={materials.wings}
          position={[0.231, 1.493, 0]}
          rotation={[-1.571, -1.569, -1.571]}
          scale={1.695}
        />
        <mesh
          name="Cube001"
          geometry={nodes.Cube001.geometry}
          material={materials.wings}
          position={[0.231, 1.493, 0]}
          rotation={[0, 0, -0.002]}
          scale={1.695}
        />
        <mesh
          name="Cylinder001"
          geometry={nodes.Cylinder001.geometry}
          material={materials.wings}
          position={[0.231, 1.493, 0]}
          rotation={[0, 0, -0.002]}
          scale={1.695}
        />
        <mesh
          name="Cylinder002"
          geometry={nodes.Cylinder002.geometry}
          material={materials.fire}
          position={[0.231, 1.493, 0]}
          rotation={[0, 0, -0.002]}
          scale={1.695}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/space-ship-scaled.glb");
